pygments: true
lsi: false
paginate: 10
permalink: pretty
sitename: kiddphunk
#feedburner.id: 'beatspixelscodelife/kJuy'
google_analytics_account: 'UA-288188-1'

commenturl: http://kiddphunk.com

exclude: [tmp, test, bin]
